services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: akasia_api
    restart: always
    expose:
      - "8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

      # Domain API
      - VIRTUAL_HOST=api-akasia.meambo.id
      - LETSENCRYPT_HOST=api-akasia.meambo.id
      - VIRTUAL_PORT=8000
    networks:
      - proxy_network

  web:
    build:
      context: ./rag-app
      dockerfile: Dockerfile
    container_name: akasia_web
    restart: always
    expose:
      - "3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=https://api-akasia.meambo.id

      # Domain Frontend
      - VIRTUAL_HOST=akasia.meambo.id
      - LETSENCRYPT_HOST=akasia.meambo.id
      - VIRTUAL_PORT=3000
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true